### PR TITLE
running

### PR DESCRIPTION
**Pull request by peggysmith20**
public class running
{
	
	
	private double endTime;

	
	
	private double max_time;

	
	public running(){
		
	}

	
	public running(double endTime) {
		
	}

	public void setEndTime(double endTime) {
		
	}

	
	public double getEndTime() {
		
		return 0.0;
	}

	
	
	public boolean exceedsMaxTime(double endTime) {
		
		return false;
	}

}

### CODE REVIEW

**Comment by carlgoshert** [comment]
Note for future: class needs to be redone to match naming convention. Merging for now

**Comment by peggysmith20** [comment]
I realized that just now I will redo it tonight.

**Comment by carlgoshert** [comment]
Awesome. No biggie

**Comment by carlgoshert** [comment]
also, comment your name into the file

**Comment by carlgoshert** [comment]
its also not being recognized as a java file. just a plain text file

**Pull request merged**
